[
  {
    "cveID": "CVE-2017-12852",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2017-08-15T16:29Z",
    "lastModifiedDate": "2019-10-03T00:03Z",
    "description": [
      {
        "lang": "en",
        "value": "The numpy.pad function in Numpy 1.13.1 and older versions is missing input validation. An empty list or ndarray will stick into an infinite loop, which can allow attackers to cause a DoS attack."
      }
    ],
    "references": [
      {
        "url": "https://github.com/numpy/numpy/issues/9560#issuecomment-322395292",
        "name": "https://github.com/numpy/numpy/issues/9560#issuecomment-322395292",
        "refsource": "CONFIRM",
        "tags": [
          "Exploit",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/BT123/testcasesForMyRequest/tree/master/CVE-2017-12852",
        "name": "https://github.com/BT123/testcasesForMyRequest/tree/master/CVE-2017-12852",
        "refsource": "MISC",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2019-6446",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2019-01-16T05:29Z",
    "lastModifiedDate": "2019-10-01T00:15Z",
    "description": [
      {
        "lang": "en",
        "value": "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources."
      }
    ],
    "references": [
      {
        "url": "https://github.com/numpy/numpy/issues/12759",
        "name": "https://github.com/numpy/numpy/issues/12759",
        "refsource": "MISC",
        "tags": [
          "Exploit",
          "Issue Tracking",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208",
        "name": "https://bugzilla.suse.com/show_bug.cgi?id=1122208",
        "refsource": "MISC",
        "tags": [
          "Exploit",
          "Issue Tracking",
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://www.securityfocus.com/bid/106670",
        "name": "106670",
        "refsource": "BID",
        "tags": [
          "Third Party Advisory",
          "VDB Entry"
        ]
      },
      {
        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/",
        "name": "FEDORA-2019-1dfe95a864",
        "refsource": "FEDORA",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html",
        "name": "openSUSE-SU-2019:2227",
        "refsource": "SUSE",
        "tags": []
      },
      {
        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html",
        "name": "openSUSE-SU-2019:2225",
        "refsource": "SUSE",
        "tags": []
      },
      {
        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html",
        "name": "openSUSE-SU-2019:2259",
        "refsource": "SUSE",
        "tags": []
      },
      {
        "url": "https://access.redhat.com/errata/RHSA-2019:3335",
        "name": "RHSA-2019:3335",
        "refsource": "REDHAT",
        "tags": []
      },
      {
        "url": "https://access.redhat.com/errata/RHSA-2019:3704",
        "name": "RHSA-2019:3704",
        "refsource": "REDHAT",
        "tags": []
      }
    ]
  },
  {
    "cveID": "CVE-2014-1859",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2018-01-08T19:29Z",
    "lastModifiedDate": "2019-04-22T17:48Z",
    "description": [
      {
        "lang": "en",
        "value": "(1) core/tests/test_memmap.py, (2) core/tests/test_multiarray.py, (3) f2py/f2py2e.py, and (4) lib/tests/test_io.py in NumPy before 1.8.1 allow local users to write to arbitrary files via a symlink attack on a temporary file."
      }
    ],
    "references": [
      {
        "url": "https://github.com/numpy/numpy/pull/4262",
        "name": "https://github.com/numpy/numpy/pull/4262",
        "refsource": "CONFIRM",
        "tags": [
          "Issue Tracking",
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15",
        "name": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst",
        "name": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst",
        "refsource": "CONFIRM",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/91317",
        "name": "numpy-cve20141859-symlink(91317)",
        "refsource": "XF",
        "tags": [
          "Issue Tracking",
          "Third Party Advisory",
          "VDB Entry"
        ]
      },
      {
        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009",
        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009",
        "refsource": "CONFIRM",
        "tags": [
          "Issue Tracking",
          "Patch"
        ]
      },
      {
        "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778",
        "name": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778",
        "refsource": "CONFIRM",
        "tags": [
          "Issue Tracking",
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://www.securityfocus.com/bid/65440",
        "name": "65440",
        "refsource": "BID",
        "tags": [
          "Third Party Advisory",
          "VDB Entry"
        ]
      },
      {
        "url": "http://www.openwall.com/lists/oss-security/2014/02/08/3",
        "name": "[oss-security] 20140207 Re: CVE request: f2py insecure temporary file use",
        "refsource": "MLIST",
        "tags": [
          "Issue Tracking",
          "Mailing List",
          "Patch",
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html",
        "name": "FEDORA-2014-2387",
        "refsource": "FEDORA",
        "tags": [
          "Issue Tracking",
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html",
        "name": "FEDORA-2014-2289",
        "refsource": "FEDORA",
        "tags": [
          "Issue Tracking",
          "Third Party Advisory"
        ]
      }
    ]
  },
  {
    "cveID": "CVE-2014-1858",
    "cveASSIGNER": "cve@mitre.org",
    "publishedDate": "2018-01-08T19:29Z",
    "lastModifiedDate": "2018-01-30T14:44Z",
    "description": [
      {
        "lang": "en",
        "value": "__init__.py in f2py in NumPy before 1.8.1 allows local users to write to arbitrary files via a symlink attack on a temporary file."
      }
    ],
    "references": [
      {
        "url": "https://github.com/numpy/numpy/pull/4262",
        "name": "https://github.com/numpy/numpy/pull/4262",
        "refsource": "CONFIRM",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15",
        "name": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15",
        "refsource": "CONFIRM",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst",
        "name": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst",
        "refsource": "CONFIRM",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/91318",
        "name": "numpy-cve20141858-symlink(91318)",
        "refsource": "XF",
        "tags": [
          "Third Party Advisory",
          "VDB Entry"
        ]
      },
      {
        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009",
        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009",
        "refsource": "CONFIRM",
        "tags": [
          "Issue Tracking",
          "Third Party Advisory"
        ]
      },
      {
        "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778",
        "name": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778",
        "refsource": "CONFIRM",
        "tags": [
          "Mailing List",
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://www.securityfocus.com/bid/65441",
        "name": "65441",
        "refsource": "BID",
        "tags": [
          "Third Party Advisory",
          "VDB Entry"
        ]
      },
      {
        "url": "http://www.openwall.com/lists/oss-security/2014/02/08/3",
        "name": "[oss-security] 20140207 Re: CVE request: f2py insecure temporary file use",
        "refsource": "MLIST",
        "tags": [
          "Mailing List",
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html",
        "name": "FEDORA-2014-2387",
        "refsource": "FEDORA",
        "tags": [
          "Third Party Advisory"
        ]
      },
      {
        "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html",
        "name": "FEDORA-2014-2289",
        "refsource": "FEDORA",
        "tags": [
          "Third Party Advisory"
        ]
      }
    ]
  }
]